package Tabilet::Schema::MySQLFacebook;

sub a2j {
    return '["'.join('","',@_).'"]';
}

sub set_mysql_facebook {
  my $self  = shift;
  my ($report) = @_;

  my $dbh  = $self->{DBH};
  my $ARGS = $self->{ARGS};

  my $table_name  = $ARGS->{table_name};
  my $proc_name   = $ARGS->{proc_name};
  my $field_id    = $ARGS->{field_id};
  my $field_login = $ARGS->{field_login};
  my $field_firstname= $ARGS->{field_firstname};
  my $field_lastname= $ARGS->{field_lastname};

  my $str = qq~CREATE TABLE IF NOT EXISTS $table_name (
  $field_id int unsigned not null,
  $field_login varchar(255) NOT NULL DEFAULT '',
  $field_firstname varchar(255) DEFAULT NULL,
  $field_lastname varchar(255) DEFAULT NULL,

  access_token  text,
  expires_in    varchar(255) DEFAULT NULL,
  id            varchar(255) DEFAULT NULL,

  status enum('Yes','No') DEFAULT 'Yes',
  created datetime DEFAULT NULL,
  updated datetime DEFAULT NULL,
  PRIMARY KEY ($field_id),
  KEY $field_login ($field_login(32))
) ENGINE=InnoDB DEFAULT CHARSET=utf8~;
  my @add = ($field_id, $field_login, $field_firstname, $field_lastname, "status", "created");
  my @add2= qw(access_token expires_in id);
  push @{$report->{tb}}, {is_login=>1, is_tabilet=>1, topics_pars=>a2j(@add,@add2), edit_pars=>a2j(@add,@add2), update_pars=>a2j(@add), current_key=>$field_id, statement=>$str, table_name=>$table_name, projectid=>$ARGS->{projectid}, table_comment=>'Generated By Tabilet', created=>$ARGS->{created}};

  my $ret = $dbh->do(
qq~DROP TABLE IF EXISTS $table_name~) and $dbh->do($str);
  return $dbh->errstr unless $ret;

  my $str_p = qq~CREATE PROCEDURE $proc_name (
IN in_email         VARCHAR(255),
IN in_first_name    VARCHAR(255),
IN in_last_name   VARCHAR(255),
IN in_access_token  TEXT,
IN in_expires_in    INT,
in in_id            VARCHAR(255),

OUT out_id        INT UNSIGNED,
OUT out_login     varchar(255),
OUT out_firstname varchar(255),
OUT out_lastname  varchar(255))
BEGIN
DECLARE s VARCHAR(10);
SELECT $field_id, $field_login, $field_firstname, $field_lastname, status INTO out_id, out_login, out_firstname, out_lastname, s FROM $table_name WHERE $field_login = in_email;

IF (out_id AND s='No') THEN
    SELECT '1030' INTO out_id;
ELSEIF (out_id) THEN
    UPDATE $table_name SET $field_firstname=in_first_name, $field_lastname=in_last_name, access_token=in_access_token, expires_in=in_expires_in, id=in_id, updated=NOW() WHERE $field_login = in_email;
ELSE
    INSERT INTO $table_name VALUES (FLOOR(RAND()*4294967296), in_email, in_given_name, in_family_name, in_access_token, in_expires_in, in_id, 'Yes', NOW(), NOW());
    SELECT $field_id, $field_login, $field_firstname, $field_lastname INTO out_id, out_login, out_firstname, out_lastname FROM $table_name WHERE $field_login = in_email;
END IF;

END~;

  push @{$report->{sp}}, {is_tabilet=>1, statement=>$str_p, procedure_name=>$proc_name, projectid=>$ARGS->{projectid}, created=>$ARGS->{created}};

  my $ret = $dbh->do(
qq~DROP PROCEDURE IF EXISTS $proc_name~) and $dbh->do(
$str_p);

  return $dbh->errstr;
}

1;
