package Tabilet::Schema::PostgresFacebook;

use strict;

sub a2j {
	return '["'.join('","',@_).'"]';
}

sub set_postgres_facebook {
  my $self  = shift;
  my ($report) = @_;

  my $dbh  = $self->{DBH};
  my $ARGS = $self->{ARGS};

  my $table_name  = $ARGS->{table_name};
  my $proc_name   = $ARGS->{proc_name};
  my $field_id    = $ARGS->{field_id};
  my $field_login = $ARGS->{field_login};
  my $field_firstname= $ARGS->{field_firstname};
  my $field_lastname= $ARGS->{field_lastname};

  my $str = qq~CREATE TABLE IF NOT EXISTS $table_name (
  $field_id integer PRIMARY KEY,
  $field_login varchar(32) NOT NULL DEFAULT '',
  $field_firstname varchar(40) DEFAULT NULL,
  $field_lastname varchar(40) DEFAULT NULL,

  access_token  text,
  expires_in    varchar(32) DEFAULT NULL,
  id            varchar(255) DEFAULT NULL,

  status BOOLEAN NOT NULL DEFAULT TRUE,
  created TIMESTAMP DEFAULT NOW(),
  updated TIMESTAMP DEFAULT NOW(),
  UNIQUE ($field_login)
)~;
  my @add = ($field_id, $field_login, $field_firstname, $field_lastname, "status", "created");
  my @add2= qw(access_token expires_in id id_token refresh_token picture);
  push @{$report->{tb}}, {is_login=>1, is_tabilet=>1, topics_pars=>a2j(@add,@add2), edit_pars=>a2j(@add,@add2), update_pars=>a2j(@add), current_key=>$field_id, statement=>$str, table_name=>$table_name, projectid=>$ARGS->{projectid}, table_comment=>'Generated By Tabilet', created=>$ARGS->{created}};

  my $ret = $dbh->do(
qq~DROP TABLE IF EXISTS $table_name~) and $dbh->do($str);
  return $dbh->errstr unless $ret;

  my $str_p = qq~CREATE PROCEDURE $proc_name (
in_email         IN VARCHAR(32), in_given_name    IN VARCHAR(40),
in_family_name   IN VARCHAR(40), in_access_token  IN TEXT,
in_expires_in    IN INTEGER,     in_id            IN VARCHAR(255),
out_id        INOUT INTEGER,     out_login     INOUT varchar(32),
out_firstname INOUT varchar(40), out_lastname  INOUT varchar(40))
LANGUAGE plpgsql
AS \$\$
DECLARE
  c1 INTEGER;
  c2 INTEGER;
  s  BOOLEAN;
BEGIN
SELECT $field_id, $field_login, $field_firstname, $field_lastname, status INTO out_id, out_login, out_firstname, out_lastname, s FROM $table_name WHERE $field_login = in_email;

IF (out_id AND s=FALSE) THEN
    SELECT '1030' INTO out_id;
ELSEIF (out_id) THEN
    UPDATE $table_name SET $field_firstname=in_given_name, $field_lastname=in_family_name, access_token=in_access_token, expires_in=in_expires_in, id=in_id, updated=NOW() WHERE $field_login = in_email;
    COMMIT;
ELSE
    INSERT INTO $table_name VALUES (FLOOR(RANDOM()*4294967296), in_email, in_given_name, in_family_name, in_access_token, in_expires_in, in_id, 'Yes', NOW(), NOW());
    SELECT $field_id, $field_login, $field_firstname, $field_lastname INTO out_id, out_login, out_firstname, out_lastname FROM $table_name WHERE $field_login = in_email;
    COMMIT;
END IF;
END;
\$\$;~;
  push @{$report->{sp}}, {is_tabilet=>1, statement=>$str_p, procedure_name=>$proc_name, projectid=>$ARGS->{projectid}, created=>$ARGS->{created}};

  my $ret = $dbh->do(
qq~DROP PROCEDURE IF EXISTS $proc_name~) and $dbh->do(
$str_p);

  return $dbh->errstr;
}

1;
