CREATE TABLE `Book3_csv` (
  `tabilet_id` int(11) NOT NULL AUTO_INCREMENT,
  `RECALL_NUMBER_NUM` varchar(255) DEFAULT NULL,
  `YEAR` int(11) DEFAULT NULL,
  `MANUFACTURER_RECALL_NO_TXT` varchar(255) DEFAULT NULL,
  `CATEGORY_ETXT` varchar(255) DEFAULT NULL,
  `CATEGORY_FTXT` varchar(255) DEFAULT NULL,
  `MAKE_NAME_NM` varchar(255) DEFAULT NULL,
  `MODEL_NAME_NM` varchar(255) DEFAULT NULL,
  `UNIT_AFFECTED_NBR` double DEFAULT NULL,
  `SYSTEM_TYPE_ETXT` varchar(255) DEFAULT NULL,
  `SYSTEM_TYPE_FTXT` varchar(255) DEFAULT NULL,
  `NOTIFICATION_TYPE_ETXT` varchar(255) DEFAULT NULL,
  `NOTIFICATION_TYPE_FTXT` varchar(255) DEFAULT NULL,
  `COMMENT_ETXT` text,
  `COMMENT_FTXT` varchar(255) DEFAULT NULL,
  `RECALL_DATE_DTE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`tabilet_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
